travis:
  secure:
    BINSTAR_TOKEN: NLZvUw2FVyi3jeew99rvY8Xmso0KQ7liD9Dbp2aWYlzaqRAxeEaOWTblq8i1wj6pH47GRxgWylLr8nBgOrrh/cNwgLwOzXOXAKJXaUsIJYqtVV5HbJzUb281OlYCqm8w9C7shwUE3LL77rje1LQ6ZBcxsCIws6G1mFYFCm7EDuvU7IRlhHtkMYy8Sz9HgVTKepFz5IldMHXqD/kBTprmx1alqmbkh9sSAkaoHUdj/nqqhKnxQsoKuzHKiavqrPyM47MJWPR8XzKSknUBs03WwI4xTe/TfIUVvfWRxF19hgNXRaGjDdeEk7DVBjcW5k3dfec1xgPtVPVtoXWNzDf4o0fVEx7AN5SoDKACx3VpNK9vPluGzC9yvKxs8Ko2qWr3jFWGiNE6efDIY648DISqdvbnuOqhMoYXqNTCwy0g3sX58MoG0Wtdmi/nrdqWBxXHyDjefoGXjpe1OcvaXJHmPCImtCmRR42cZMr9e0V9h41Hwh73TQX49tjvjMX0Tkm2Lc/I+UDYOvC4yDzV1HB3gPll8umgo/3ZVhZFilunuKiQ/tECPfRpCvkMNXRUxzCOp7RCWqukNHqNHuuSfKZ1OMqIE9YWEbEkXiTP+boXSRNKJ6NZBi+Xnjtu1iWM3uQpqPOom0glTlQCFhpx2Kj+i/HE32Eq5i2U35oZ3V3tgpI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
